### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by akm190** [alexlee-gk/video_prediction#1]
Hi, 
Approximately how long does it take to train this network. I tried training it on a PC with no GPUs, it takes around 5 mins for each iteration. Am I doing something wrong? Is it significantly faster with GPUs?

Thanks.

**Comment by alexlee-gk** [comment]
Yes, it is significantly faster with GPUs. The deterministic and VAE models should take about 1.5 days to train for 300k iterations,  using a batch size of 16 and a single Titan Xp GPU. The GAN and VAE-GAN models take longer. The training speeds are approximately as follows.

| Model variant  | Time per iteration  |
| -------------- | -------------------:|
| deterministic  |                0.4s |
| VAE            |                0.5s |
| GAN            |                0.8s |
| VAE-GAN (SAVP) |                1.6s |

Especially for the GAN and VAE-GAN models, the training speeds are considerably faster with multi-GPU training. The training speeds are improved even further with Volta GPUs.

**Comment by akm190** [comment]
Thanks for your response. It was really helpful.
