### ISSUE TITLE
ModuleNotFoundError: no module named 'video_prediction'

### ISSUE THREAD

**Issue by happyday521** [alexlee-gk/video_prediction#15]
Hello,

I implemented the steps according to the instructions and then run:
CUDA_VISIBLE_DEVICES=0 python scripts/train.py --input_dir data/bair --dataset bair \
  --model savp --model_hparams_dict hparams/bair_action_free/ours_savp/model_hparams.json \
  --output_dir logs/bair_action_free/ours_savp

Then error occurs: ModuleNotFoundError: no module named 'video_prediction'.

It seems everything is right, but how does it happen.

I also try to add  sys.append(path) before import. However , it doesn't help.

I really don't know where is the problem. Can you help me? Thanks!

Thank you.

**Comment by alexlee-gk** [comment]
This seems to happen with python >= 3.6 due to how imports are handled. You should add the root directory of the repo to the PYTHONPATH. I added this note to the README under "Miscellaneous installation considerations". Let me know if the problem still persists.

**Comment by happyday521** [comment]
@alexlee-gk Sorry foe my later reply. I will try your method and tell you about the follow-up results later. Thanks firstly!

**Comment by happyday521** [comment]
I have solevd it！Thanks！
