### ISSUE TITLE
About the image reshaping when preparing my own dataset

### ISSUE THREAD

**Issue by happyday521** [alexlee-gk/video_prediction#16]
Hi, Alex!

Thanks for releasing the code! I am having some trouble running the code. I want to run your code on my own dataset and I preprocess it into TFRecords files and define a class for it(based on kth_dataset.py) Besides, I need to change the image size to 128x128.  

Can you tell me what and where should I modify when I prepare my own dataset (128x128, RGB) except what I have done? Need I modify the network architecture (such as layers) to adjust to my resolution(128x128)? 
 Thanks very much! Look forward to your reply!

**Comment by tangjilin** [comment]
The bug information:
![5](https://user-images.githubusercontent.com/35884085/50581338-ccc5b080-0e93-11e9-978f-3fdfab5b2567.png)

**Comment by alexlee-gk** [comment]
In the `kth_dataset.py` script, you can preprocess to 128x128 images by passing the flag `--image_size 128`. The kth script assumes that the images are grayscale so it [only keeps one of the channels](https://github.com/alexlee-gk/video_prediction/blob/master/video_prediction/datasets/kth_dataset.py#L118), which you might not want to do for your dataset. 

The model should already work for 128x128 images, but it uses a lot of memory. I haven't tried much architectures for 128x128 resolution so you might want to adjust the [layer specification](https://github.com/alexlee-gk/video_prediction/blob/master/video_prediction/models/savp_model.py#L199-L210) so you end up using less memory.

**Comment by happyday521** [comment]
Got it. Thanks!
