### ISSUE TITLE
About sequence length

### ISSUE THREAD

**Issue by happyday521** [alexlee-gk/video_prediction#17]
Hi!
I train my model with context_frames=10 and sequence_length=30, in other words, aiming to predict the next 20 frames. (Because of my Hardware limitation).
I wonder whether I can generate the next 30 frames(rather than 20) when I test the model. Can I set the  context_frames=10 and sequence_length=40 directly when testing? Or need I modify anything? 
Thanks!

**Comment by alexlee-gk** [comment]
Yes, you can do that. The test sequence length doesn't have to be the same as the training sequence length. If you are evaluating on the full-reference metrics (i.e. the metrics that need a ground-truth sequence), then you are limited by the length of the ground-truth videos. If you are just generating frames, those predictions can be arbitrarily long.

**Comment by happyday521** [comment]
Thanks！Closed.
