### ISSUE TITLE
A question about standard deviation for drawing

### ISSUE THREAD

**Issue by shijiwensjw** [alexlee-gk/video_prediction#18]
[https://github.com/alexlee-gk/video_prediction/blob/master/scripts/plot_results.py](url)#L25
In this line, I wonder why you use `metric_se = np.std(metric, axis=0) / np.sqrt(len(metric))` instead of just standard deviation `metric_se = np.std(metric, axis=0) ` ? Why is the standard deviation divided by `np.sqrt(len(metric)`?

**Comment by richzhang** [comment]
It's the [standard error](https://en.wikipedia.org/wiki/Standard_error) -- the more measurements you make, the more sure you are of the mean.

**Comment by shijiwensjw** [comment]
Thank you, richzhang,
I confused the standard deviation and the standard error, now I understand.
