### ISSUE TITLE
Deterministic network architectyre

### ISSUE THREAD

**Issue by fatemehtd** [alexlee-gk/video_prediction#19]
Hi Alex,
Thanks for releasing the code! Reading your paper, I am wondering what do you mean by deterministic model? Does it have the same architecture as the generator network with only previous frame as input and a l1 or l2 loss to construct the future frame? 

Thanks.

**Comment by alexlee-gk** [comment]
That's correct. In addition, there is no latent variable z given to the generator (or equivalently, the dimensionality of z is zero).

**Comment by fatemehtd** [comment]
Thanks for the clarification
