### ISSUE TITLE
Confused about the features' name  in BAIR dataset

### ISSUE THREAD

**Issue by Jinghui-Wang** [alexlee-gk/video_prediction#20]
Hi!
I am confused about the meaning of the features' names in BAIR dataset stored as TFRecords: 'image_aux1', 'image_main', 'endeffector_pos', 'action'. 
Could you give me a hint?

**Comment by alexlee-gk** [comment]
'image_aux1' and 'image_main' are 64x64 RGB images from two different viewpoints. 'endeffector_pos' is a 4-dimensional state vector consisting of Cartesian 3-D positions of the gripper and the rotation angle of the gripper (around the gravity axis). 'action' is a 5-dimensional vector consisting of discrete-time velocities of the state and an additional value indicating if the gripper opens or closes.

**Comment by Jinghui-Wang** [comment]
Got it! Thanks!
