### ISSUE TITLE
Issue with tensorflow 1.10

### ISSUE THREAD

**Issue by tomahawk810** [alexlee-gk/video_prediction#4]
Hi Alex,

Thanks a lot for sharing your work!

For info, I am running your code on windows, and had issues when using tensorflow 1.10.
Both for "scripts/generate.py" (error message related to shape 0 instead of shape 30 expected) and "scripts/evaluate.py" (error message related to eager execution).

Everything works fine with tensorflow 1.5.

I thought I would mention it, to save time for others that might encounter the same issue.

Regards,
Thomas.

**Comment by alexlee-gk** [comment]
Hi Thomas, thanks for reporting this! I've tried tensorflow 1.10 and 1.11, and they both work in Ubuntu 16.04. Maybe this is a problem related to windows, but I wouldn't know what it is.
